const WatchesData = [
    {
        parentId: 1,
        img: './rich-tales/watches/invicta-in8.png',
        brandimg: './rich-tales/brands-images/invicta-brand.png',
        title: 'Invicta IN8927OB',
        price: 18360,
        filters: [
            {key: 'Type', keyText: 'Male'},
            {key: 'Brand', keyText: 'Invicta'},
            {key: 'Country', keyText: 'Switzerland'},
            {key: 'Material', keyText: 'Metal'},
            {key: 'Color', keyText: 'White'},
            {key: 'Shape', keyText: 'Round'},
            {key: 'Dial', keyText: 'Classic'},
        ]
    },
    {
        parentId: 2,
        img: './rich-tales/watches/ck-k8q.png',
        brandimg: './rich-tales/brands-images/ck-brand.png',
        title: 'Calvin Klein K8Q336X2',
        price: 17900,
        filters: [
            {key: 'Type', keyText: 'Female'},
            {key: 'Brand', keyText: 'Calvin Klein'},
            {key: 'Country', keyText: 'USA'},
            {key: 'Material', keyText: 'Metal'},
            {key: 'Color', keyText: 'White'},
            {key: 'Shape', keyText: 'Round'},
            {key: 'Dial', keyText: 'Classic'},
        ]
    },
    {
        parentId: 3,
        img: './rich-tales/watches/casio-gsh.png',
        brandimg: './rich-tales/brands-images/casio-brand.png',
        title: 'Casio G-SHOCK GA-2100SKE-7AER',
        price: 11900,
        filters: [
            {key: 'Type', keyText: 'Male'},
            {key: 'Brand', keyText: 'Casio'},
            {key: 'Country', keyText: 'Japan'},
            {key: 'Material', keyText: 'Steel'},
            {key: 'Color', keyText: 'Blue'},
            {key: 'Shape', keyText: 'Round'},
            {key: 'Dial', keyText: 'Mechanical'},
        ]
    },
    {
        parentId: 4,
        img: './rich-tales/watches/rodania-r11.png',
        brandimg: './rich-tales/brands-images/rodania-brand.png',
        title: 'Rodania R11001',
        price: 19850,
        filters: [
            {key: 'Type', keyText: 'Male'},
            {key: 'Brand', keyText: 'Rodania'},
            {key: 'Country', keyText: 'Switzerland'},
            {key: 'Material', keyText: 'Metal'},
            {key: 'Color', keyText: 'White'},
            {key: 'Shape', keyText: 'Round'},
            {key: 'Dial', keyText: 'Classic'},
        ]
    },
    {
        parentId: 5,
        img: './rich-tales/watches/seiko-ssb.png',
        brandimg: './rich-tales/brands-images/seiko-brand.png',
        title: 'Seiko SSB405P1',
        price: 37660,
        filters: [
            {key: 'Type', keyText: 'Male'},
            {key: 'Brand', keyText: 'Seiko'},
            {key: 'Country', keyText: 'Japan'},
            {key: 'Material', keyText: 'Steel'},
            {key: 'Color', keyText: 'White'},
            {key: 'Shape', keyText: 'Round'},
            {key: 'Dial', keyText: 'Mechanical'},
        ]
    },
    {
        parentId: 6,
        img: './rich-tales/watches/davosa-161.png',
        brandimg: './rich-tales/brands-images/davosa-brand.png',
        title: 'DAVOSA DAV.16152740',
        price: 114760,
        filters: [
            {key: 'Type', keyText: 'Male'},
            {key: 'Brand', keyText: 'Davosa'},
            {key: 'Country', keyText: 'Switzerland'},
            {key: 'Material', keyText: 'Silver'},
            {key: 'Color', keyText: 'Blue'},
            {key: 'Shape', keyText: 'Round'},
            {key: 'Dial', keyText: 'Classic'},
        ]
    },
    {
        parentId: 7,
        img: './rich-tales/watches/hublot-gold.png',
        brandimg: './rich-tales/brands-images/hublot-brand.png',
        title: 'HUBLOT Gold Diamonds',
        price: 2970000,
        filters: [
            {key: 'Type', keyText: 'Female'},
            {key: 'Brand', keyText: 'HUBLOT'},
            {key: 'Country', keyText: 'Switzerland'},
            {key: 'Material', keyText: 'Gold'},
            {key: 'Color', keyText: 'Black'},
            {key: 'Shape', keyText: 'Round'},
            {key: 'Dial', keyText: 'Classic'},
        ]
    },
    {
        parentId: 8,
        img: './rich-tales/watches/omega-210.png',
        brandimg: './rich-tales/brands-images/omega-brand.png',
        title: 'OMEGA 21032422004001',
        price: 610000,
        filters: [
            {key: 'Type', keyText: 'Male'},
            {key: 'Brand', keyText: 'Omega'},
            {key: 'Country', keyText: 'Switzerland'},
            {key: 'Material', keyText: 'Titanium'},
            {key: 'Color', keyText: 'Black'},
            {key: 'Shape', keyText: 'Round'},
            {key: 'Dial', keyText: 'Mechanical'},
        ]
    },
    {
        parentId: 9,
        img: './rich-tales/watches/cartier-tnk.png',
        brandimg: './rich-tales/brands-images/cartier-brand.png',
        title: 'CARTIER TANK ANGLAISE',
        price: 902000,
        filters: [
            {key: 'Type', keyText: 'Female'},
            {key: 'Brand', keyText: 'Cartier'},
            {key: 'Country', keyText: 'France'},
            {key: 'Material', keyText: 'Gold'},
            {key: 'Color', keyText: 'White'},
            {key: 'Shape', keyText: 'Rectangular'},
            {key: 'Dial', keyText: 'Classic'},
        ]
    },
    {
        parentId: 10,
        img: './rich-tales/watches/seiko-ssb8.png',
        brandimg: './rich-tales/brands-images/seiko-brand.png',
        title: 'Seiko SSB321P1',
        price: 37710,
        filters: [
            {key: 'Type', keyText: 'Male'},
            {key: 'Brand', keyText: 'Seiko'},
            {key: 'Country', keyText: 'Japan'},
            {key: 'Material', keyText: 'Silver'},
            {key: 'Color', keyText: 'Blue'},
            {key: 'Shape', keyText: 'Round'},
            {key: 'Dial', keyText: 'Mechanical'},
        ]
    },
    {
        parentId: 11,
        img: './rich-tales/watches/davosa-1615.png',
        brandimg: './rich-tales/brands-images/davosa-brand.png',
        title: 'DAVOSA DAV.16151174',
        price: 74015,
        filters: [
            {key: 'Type', keyText: 'Male'},
            {key: 'Brand', keyText: 'Davosa'},
            {key: 'Country', keyText: 'Switzerland'},
            {key: 'Material', keyText: 'Silver'},
            {key: 'Color', keyText: 'Green'},
            {key: 'Shape', keyText: 'Round'},
            {key: 'Dial', keyText: 'Classic'},
        ]
    },
    {
        parentId: 12,
        img: './rich-tales/watches/ck-2520.png',
        brandimg: './rich-tales/brands-images/ck-brand.png',
        title: 'Calvin Klein 25200230',
        price: 21000,
        filters: [
            {key: 'Type', keyText: 'Female'},
            {key: 'Brand', keyText: 'Calvin Klein'},
            {key: 'Country', keyText: 'USA'},
            {key: 'Material', keyText: 'Metal'},
            {key: 'Color', keyText: 'Blue'},
            {key: 'Shape', keyText: 'Round'},
            {key: 'Dial', keyText: 'Classic'},
        ]
    },
    {
        parentId: 13,
        img: './rich-tales/watches/rodania-r200.png',
        brandimg: './rich-tales/brands-images/rodania-brand.png',
        title: 'Rodania R20005',
        price: 21000,
        filters: [
            {key: 'Type', keyText: 'Male'},
            {key: 'Brand', keyText: 'Rodania'},
            {key: 'Country', keyText: 'Switzerland'},
            {key: 'Material', keyText: 'Silver'},
            {key: 'Color', keyText: 'Green'},
            {key: 'Shape', keyText: 'Round'},
            {key: 'Dial', keyText: 'Mechanical'},
        ]
    },
    {
        parentId: 14,
        img: './rich-tales/watches/invicta-in29.png',
        brandimg: './rich-tales/brands-images/invicta-brand.png',
        title: 'Invicta IN29372',
        price: 13000,
        filters: [
            {key: 'Type', keyText: 'Male'},
            {key: 'Brand', keyText: 'Invicta'},
            {key: 'Country', keyText: 'Switzerland'},
            {key: 'Material', keyText: 'Silver'},
            {key: 'Color', keyText: 'Black'},
            {key: 'Shape', keyText: 'Round'},
            {key: 'Dial', keyText: 'Classic'},
        ]
    },
    {
        parentId: 15,
        img: './rich-tales/watches/casio-efv.png',
        brandimg: './rich-tales/brands-images/casio-brand.png',
        title: 'Casio Edifice EFV-600D-2AVUEF',
        price: 12210,
        filters: [
            {key: 'Type', keyText: 'Male'},
            {key: 'Brand', keyText: 'Casio'},
            {key: 'Country', keyText: 'Japan'},
            {key: 'Material', keyText: 'Steel'},
            {key: 'Color', keyText: 'Blue'},
            {key: 'Shape', keyText: 'Round'},
            {key: 'Dial', keyText: 'Mechanical'},
        ]
    },
    {
        parentId: 16,
        img: './rich-tales/watches/rodania-r15.png',
        brandimg: './rich-tales/brands-images/rodania-brand.png',
        title: 'Rodania R15006',
        price: 24600,
        filters: [
            {key: 'Type', keyText: 'Male'},
            {key: 'Brand', keyText: 'Rodania'},
            {key: 'Country', keyText: 'Switzerland'},
            {key: 'Material', keyText: 'Steel'},
            {key: 'Color', keyText: 'White'},
            {key: 'Shape', keyText: 'Round'},
            {key: 'Dial', keyText: 'Classic'},
        ]
    },
    {
        parentId: 17,
        img: './rich-tales/watches/hublot-orl.png',
        brandimg: './rich-tales/brands-images/hublot-brand.png',
        title: 'Orlinski King Gold Pavé',
        price: 5057000,
        filters: [
            {key: 'Type', keyText: 'Male'},
            {key: 'Brand', keyText: 'HUBLOT'},
            {key: 'Country', keyText: 'Switzerland'},
            {key: 'Material', keyText: 'Gold'},
            {key: 'Color', keyText: 'Black'},
            {key: 'Shape', keyText: 'Round'},
            {key: 'Dial', keyText: 'Classic'},
        ]
    },
    {
        parentId: 18,
        img: './rich-tales/watches/cartier-cle.png',
        brandimg: './rich-tales/brands-images/cartier-brand.png',
        title: 'CLE DE CARTIER',
        price: 276000,
        filters: [
            {key: 'Type', keyText: 'Female'},
            {key: 'Brand', keyText: 'Cartier'},
            {key: 'Country', keyText: 'France'},
            {key: 'Material', keyText: 'Titanium'},
            {key: 'Color', keyText: 'White'},
            {key: 'Shape', keyText: 'Oval'},
            {key: 'Dial', keyText: 'Classic'},
        ]
    },
    {
        parentId: 19,
        img: './rich-tales/watches/rodania-r16.png',
        brandimg: './rich-tales/brands-images/rodania-brand.png',
        title: 'Rodania R16021',
        price: 25500,
        filters: [
            {key: 'Type', keyText: 'Male'},
            {key: 'Brand', keyText: 'Rodania'},
            {key: 'Country', keyText: 'Switzerland'},
            {key: 'Material', keyText: 'Silver'},
            {key: 'Color', keyText: 'Black'},
            {key: 'Shape', keyText: 'Round'},
            {key: 'Dial', keyText: 'Mechanical'},
        ]
    },
    {
        parentId: 20,
        img: './rich-tales/watches/casio-gmw.png',
        brandimg: './rich-tales/brands-images/casio-brand.png',
        title: 'Casio G-SHOCK GMW-B5000D-1E',
        price: 79900,
        filters: [
            {key: 'Type', keyText: 'Male'},
            {key: 'Brand', keyText: 'Casio'},
            {key: 'Country', keyText: 'Japan'},
            {key: 'Material', keyText: 'Silver'},
            {key: 'Color', keyText: 'White'},
            {key: 'Shape', keyText: 'Square'},
            {key: 'Dial', keyText: 'Mechanical'},
        ]
    },
    {
        parentId: 21,
        img: './rich-tales/watches/omega-300.png',
        brandimg: './rich-tales/brands-images/omega-brand.png',
        title: 'DIVER 300M CO‑AXIAL 43.5 MM',
        price: 1205000,
        filters: [
            {key: 'Type', keyText: 'Male'},
            {key: 'Brand', keyText: 'Omega'},
            {key: 'Country', keyText: 'Switzerland'},
            {key: 'Material', keyText: 'Titanium'},
            {key: 'Color', keyText: 'Black'},
            {key: 'Shape', keyText: 'Round'},
            {key: 'Dial', keyText: 'Classic'},
        ]
    },
    {
        parentId: 22,
        img: './rich-tales/watches/invicta-143.png',
        brandimg: './rich-tales/brands-images/invicta-brand.png',
        title: 'Invicta IN14361',
        price: 12900,
        filters: [
            {key: 'Type', keyText: 'Female'},
            {key: 'Brand', keyText: 'Invicta'},
            {key: 'Country', keyText: 'Switzerland'},
            {key: 'Material', keyText: 'Steel'},
            {key: 'Color', keyText: 'Blue'},
            {key: 'Shape', keyText: 'Round'},
            {key: 'Dial', keyText: 'Classic'},
        ]
    },
    {
        parentId: 23,
        img: './rich-tales/watches/ck-252.png',
        brandimg: './rich-tales/brands-images/ck-brand.png',
        title: 'Calvin Klein 25200267',
        price: 26900,
        filters: [
            {key: 'Type', keyText: 'Male'},
            {key: 'Brand', keyText: 'Calvin Klein'},
            {key: 'Country', keyText: 'USA'},
            {key: 'Material', keyText: 'Steel'},
            {key: 'Color', keyText: 'Black'},
            {key: 'Shape', keyText: 'Round'},
            {key: 'Dial', keyText: 'Mechanical'},
        ]
    },
    {
        parentId: 24,
        img: './rich-tales/watches/davosa-167.png',
        brandimg: './rich-tales/brands-images/davosa-brand.png',
        title: 'DAVOSA DAV.16756215',
        price: 22410,
        filters: [
            {key: 'Type', keyText: 'Female'},
            {key: 'Brand', keyText: 'Davosa'},
            {key: 'Country', keyText: 'Switzerland'},
            {key: 'Material', keyText: 'Silver'},
            {key: 'Color', keyText: 'White'},
            {key: 'Shape', keyText: 'Round'},
            {key: 'Dial', keyText: 'Classic'},
        ]
    },
];

export default WatchesData;